apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: react-topology
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: react-topology
    app.kubernetes.io/part-of: test-app-1
  name: react-topology
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: react-topology
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: react-topology
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jephilli-tenant/test-app-1/react-topology@sha256:bee0dd3145620cdcea39bfe897fc8ce6b64f9f45dfad43b095de72f8320b40d8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
