apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: react-topology
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: react-topology
    app.kubernetes.io/part-of: test-app-1
  name: react-topologylgdi
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: react-topology
    weight: null
status: {}
